Services refactoring
Grafikart/Grafikart.fr pull request #87
Opened 2020-08-27 21:26 UTC by oussaka

Bonjour,

J'ai refactorisé la déclaration de services et update les recipes.

2020-08-27 21:50 UTC, Grafikart requested changes

2020-08-27 21:50 UTC, Grafikart commented on bin/console
> +(new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
A quoi correspond cette modification ?

2020-08-27 21:50 UTC, Grafikart commented on bin/console
> +if (!class_exists(Application::class) || !class_exists(Dotenv::class)) {
Pourquoi cet ajout ? Cela correspond à quoi ?

2020-08-27 21:50 UTC, Grafikart commented on config/services.yaml
> +  twitter_secret:   '%env(resolve:TWITTER_SECRET)%'
Tu as utilisé un outil pour aligner ou tu l'as fait manuellement ?

2020-08-27 21:50 UTC, Grafikart commented on public/index.php
> +(new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
A quoi correspond cette modification ?

2020-08-27 22:40 UTC, oussaka commented on bin/console
> +(new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
Cette modification vient du recipe console. La synchronisation du recipe console (**composer recipes symfony/console**), modifie deux fichiers:

```
Created bin/console
Created config/bootstrap.php
```
Les fichier modifie par le recipes console sont ici : https://github.com/symfony/recipes/tree/master/symfony/console
Il est conseillé d'avoir les mêmes fichiers pour uniformiser les applications SF.

Pour plus de détails (https://symfonycasts.com/screencast/symfony5-upgrade/console-recipe)

2020-08-27 22:43 UTC, oussaka commented on config/services.yaml
> +  twitter_secret:   '%env(resolve:TWITTER_SECRET)%'
C'est l'action "**Reformat code**" keymap par défaut est : **Ctrl+Alt+L**

2020-08-27 22:44 UTC, oussaka commented on public/index.php
> +(new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
Même chose que console. Ce fichier est modifié par une synchronisation de recipes.

2020-08-30 12:38 UTC, merged

2020-08-30 12:38 UTC, Grafikart commented
Merci c'est mergé !